version: "3.8"
services:
  client:
    build: ./client
    ports:
      - "3034:3032" # outer:inner
    environment:
      - INFLUX_URL=http://192.168.0.17:8087
    depends_on:
      - db
  # server:
  #   build: ./server
  db:
    image: influxdb:2.0-alpine
    ports:
      - "8087:8086"
    volumes:
      - "./influx-data:/var/lib/influxdb2"
