version: "3.9"
services:
  client:
    build: ./client
  server:
    build: ./server
  db:
    image: influxdb:2.0-alpine
# docker run --rm --name loradatainflux -p 8086:8086 \
      # -v $PWD/influx:/var/lib/influxdb2 \
      # influxdb:2.0-alpine        