version: "3.8"
services:
  client:
    build: ./client
    ports:
      - "3034:3032" # outer:inner
    environment:
      - INFLUX_URL=http://192.168.0.17:8086
  # server:
  #   build: ./server
  # db:
  #   image: influxdb:2.0-alpine
# docker run --rm --name loradatainflux -p 8086:8086 \
      # -v $PWD/influx:/var/lib/influxdb2 \
      # influxdb:2.0-alpine        